#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Credenciales de FreeBusy para una cuenta de Google de prueba (ADR-0004):
# GOOGLE_* en apps/web/.env.local y GOOGLE_TEST_* como secretos de GitHub para CI.
cd "$(dirname "$0")/.."
# Sin terminal (p. ej. el prefijo `!` de Claude Code) cada pregunta lee vacío y el wizard pasaría de largo.
[[ -t 0 ]] || { echo "Corre este wizard en una terminal interactiva: scripts/credenciales-google.sh" >&2; exit 1; }
ENV_FILE="apps/web/.env.local"
ALCANCE="https://www.googleapis.com/auth/calendar.freebusy"
PLAYGROUND="https://developers.google.com/oauthplayground"

TOTAL_STAGES=7
TOTAL_MINUTES=20

banner "Credenciales de Google FreeBusy para pruebas"

stage "Proyecto de Google Cloud" 2
say "Usa la cuenta de Google de PRUEBA, no la del gestor."
open_url "https://console.cloud.google.com/projectcreate"
step "Crea un proyecto (p. ej. «ghycs-pruebas») o cancela y elige uno existente."
step "Comprueba que ese proyecto quede seleccionado arriba, en el selector de proyectos."
pause "¿Proyecto seleccionado? Enter para seguir"

stage "Habilitar Google Calendar API" 1
open_url "https://console.cloud.google.com/apis/library/calendar-json.googleapis.com"
step "Pulsa «Habilitar» (si dice «Administrar», ya está habilitada)."
pause "¿Habilitada? Enter para seguir"

stage "Pantalla de consentimiento OAuth" 4
open_url "https://console.cloud.google.com/auth/overview"
step "Si aparece «Comenzar»: nombre de la app, correo de asistencia, público «Externo», correo de contacto, acepta y crea."
step "Ve a «Acceso a los datos» → «Agregar o quitar permisos»."
step "En «Agregar permisos manualmente» pega: $ALCANCE → «Agregar a la tabla» → «Actualizar» → «Guardar»."
step "Ve a «Público» → «Publicar la app» → confirma. Debe quedar «En producción»."
warn "En «Prueba» el refresh token caduca a los 7 días y CI fallaría con invalid_grant."
note "Sin verificar la app funciona: Google solo muestra un aviso al autorizar."
pause "¿App en producción con el permiso freebusy? Enter para seguir"

stage "Cliente OAuth" 3
open_url "https://console.cloud.google.com/auth/clients/create"
step "Tipo de aplicación: «Aplicación web». Nombre: «ghycs-pruebas»."
step "En «URI de redireccionamiento autorizados» agrega: $PLAYGROUND"
step "Pulsa «Crear» y copia el ID de cliente y el secreto (el secreto puede mostrarse una sola vez)."
ask GOOGLE_CLIENT_ID "Pega el ID de cliente (termina en .apps.googleusercontent.com):"
ask_secret GOOGLE_CLIENT_SECRET "Pega el secreto del cliente:"

stage "Refresh token en OAuth Playground" 5
open_url "$PLAYGROUND"
step "Engrane (arriba a la derecha): marca «Use your own OAuth credentials» y pega el ID y el secreto."
step "En ese mismo panel deja «Access type: Offline» y «Force prompt: Consent Screen». Cierra."
step "Paso 1, «Input your own scopes»: pega $ALCANCE → «Authorize APIs»."
step "Entra con la cuenta de prueba. Ante «Google no verificó esta app»: «Configuración avanzada» → «Ir a …» → «Continuar»."
step "Paso 2: «Exchange authorization code for tokens» y copia el «Refresh token»."
ask_secret GOOGLE_REFRESH_TOKEN "Pega el refresh token:"

stage "Calendario a consultar" 2
say "«primary» es el calendario principal de la cuenta de prueba."
note "Para otro: Google Calendar → Configuración → el calendario → «Integrar el calendario» → «ID del calendario»."
ask GOOGLE_CALENDAR_ID "ID del calendario (Enter para «primary»):"
GOOGLE_CALENDAR_ID="${GOOGLE_CALENDAR_ID:-primary}"

stage "Verificar y guardar" 3
say "Consulto FreeBusy de los próximos 7 días con estas credenciales…"
ACCESO=$(curl -s https://oauth2.googleapis.com/token \
  -d grant_type=refresh_token -d client_id="$GOOGLE_CLIENT_ID" \
  -d client_secret="$GOOGLE_CLIENT_SECRET" -d refresh_token="$GOOGLE_REFRESH_TOKEN" |
  sed -n 's/.*"access_token": *"\([^"]*\)".*/\1/p')
DESDE=$(date -u +%Y-%m-%dT%H:%M:%SZ)
HASTA=$(date -u -v+7d +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || date -u -d '+7 days' +%Y-%m-%dT%H:%M:%SZ)
RESPUESTA=""
[[ -n "$ACCESO" ]] && RESPUESTA=$(curl -s https://www.googleapis.com/calendar/v3/freeBusy \
  -H "authorization: Bearer $ACCESO" -H "content-type: application/json" \
  -d "{\"timeMin\":\"$DESDE\",\"timeMax\":\"$HASTA\",\"items\":[{\"id\":\"$GOOGLE_CALENDAR_ID\"}]}")
if [[ "$RESPUESTA" == *'"busy"'* && "$RESPUESTA" != *'"errors"'* ]]; then
  printf '  %s✓ FreeBusy respondió%s\n' "$GREEN" "$RESET"
else
  warn "La verificación falló. Respuesta: ${RESPUESTA:-sin access token (revisa ID, secreto y refresh token)}"
  confirm "¿Guardar de todos modos?" || { warn "No guardé nada. Vuelve a correr el wizard."; exit 1; }
fi
write_env GOOGLE_CLIENT_ID "$GOOGLE_CLIENT_ID"
write_env GOOGLE_CLIENT_SECRET "$GOOGLE_CLIENT_SECRET"
write_env GOOGLE_REFRESH_TOKEN "$GOOGLE_REFRESH_TOKEN"
write_env GOOGLE_CALENDAR_ID "$GOOGLE_CALENDAR_ID"
if confirm "¿Subir las credenciales como secretos GOOGLE_TEST_* de GitHub (reemplaza los existentes)?"; then
  set_secret GOOGLE_TEST_CLIENT_ID "$GOOGLE_CLIENT_ID"
  set_secret GOOGLE_TEST_CLIENT_SECRET "$GOOGLE_CLIENT_SECRET"
  set_secret GOOGLE_TEST_REFRESH_TOKEN "$GOOGLE_REFRESH_TOKEN"
  set_secret GOOGLE_TEST_CALENDAR_ID "$GOOGLE_CALENDAR_ID"
else
  SKIPPED+=("secretos GOOGLE_TEST_* de GitHub (vuelve a correr el wizard)")
fi

finish
note "Contrato contra Google en local:"
note "  set -a; . $ENV_FILE; set +a; pnpm --filter @ghycs/web exec vitest run ocupacion.contrato"
